/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:614cca95-8441-41d9-83d9-a0625227707e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_WO7hglmIn",
    "aws_user_pools_web_client_id": "3ke3nsm8km3fjla4uebborvp7p",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://a7vc57x5njdxrme3vyf4kz65ma.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-wr3dfse7xfdfjafxlyylb3ysrm",
    "aws_user_files_s3_bucket": "littlepawsplace6585b24393184f21886a1d53f017e6176d13b-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
